image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - apk --no-cache add git
  - git submodule sync --recursive
  - git submodule update --recursive --remote


build_image:
  script:
    - docker build -t vvp-web .
