version: '3'

services:
  vvp-web:
    depends_on:
      - redis
      - git-http
      - ssh-daemon
    build: .
    environment:
      - SSHD_USERNAME=root
      - SSHD_PASSWORD=git_sshd
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.50

  nginx:
    build: ./container/nginx
    restart: always
    networks:
      public:
        ipv4_address: 10.10.0.10
      internal:
        ipv4_address: 10.11.0.10
    ports:
      - "443:443"
      - "80:80"

  redis:
    image: "redis:alpine"
    networks:
      internal:
        ipv4_address: 10.11.0.20
    environment:
      - REDIS_HOST=10.11.0.20 #TODO: @vscharf - why?
    volumes:
      - ./redis:/data

  git-http:
    build: ./container/git-http
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.21
    volumes:
      - ./git:/git

  ssh-daemon:
    build: ./container/ssh-daemon
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.22
    volumes:
      - ./git:/git

networks:
  public:
    # use the bridge driver, but enable IPv6
    # subnet "10.10.0.0/24"
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  internal:
    # use bridge driver in subnet "10.11.0.0/24"
    driver: overlay
    internal: true
    ipam:
      config:
        - subnet: 10.11.0.0/24