#  Developed by Nicholas Dehnen & Vincent Scharf.
#  Copyright (c) 2019 Deutsche Telekom Intellectual Property.
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

version: '3'

services:

  python3-sanic:
    image: python3-sanic
    build: ./container/python3-sanic

  vvp-web:
    depends_on:
      - python3-sanic
      - redis
      - git-http
      - ssh-daemon
    build: .
    environment:
      - SSHD_USERNAME=root
      - SSHD_PASSWORD=git_sshd
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.50

  nginx:
    build: ./container/nginx
    restart: always
    networks:
      public:
        ipv4_address: 10.10.0.10
      internal:
        ipv4_address: 10.11.0.10
    ports:
      - "443:443"
      - "80:80"

  redis:
    image: "redis:alpine"
    networks:
      internal:
        ipv4_address: 10.11.0.20
    volumes:
      - ./redis:/data:z
  git-http:
    build: ./container/git-http
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.21
    volumes:
      - ./git:/git:z

  ssh-daemon:
    build: ./container/ssh-daemon
    restart: always
    networks:
      internal:
        ipv4_address: 10.11.0.22
    volumes:
      - ./git:/git:z

networks:
  public:
    # use the bridge driver, but enable IPv6
    # subnet "10.10.0.0/24"
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  internal:
    # use bridge driver in subnet "10.11.0.0/24"
    driver: overlay
    internal: true
    ipam:
      config:
        - subnet: 10.11.0.0/24